### ISSUE TITLE
Gui assumption causes OSX 10.6 vim problems

### ISSUE THREAD

**Issue by wohali** [jimenezrick/vimerl#17]
Such a simple tweak to compiler/erlang.vim that I'm not bothering forking and issuing a pull request.

On OSX 10.6, running vim from the CLI on a trivial .erl file results in the following:

```
Error detected while processing /Users/joant/.vim/bundle/jimenezrick-vimerl/compiler/erlang.vim:
line   34:
E319: Sorry, the command is not available in this version: sign define ErlangError   text=>> texthl=Error
line   35:
E319: Sorry, the command is not available in this version: sign define ErlangWarning text=>> texthl=Todo
```

Wrap those two lines in:

```
if has('gui_running')
    ....
endif
```

and the error goes away.

**Comment by jimenezrick** [comment]
I think this is related to the Vim version, not to if Vim is running with GUI or on CLI mode. The Vim that comes with OS X is 7.2, Vimerl requires version 7.3 in order to work syntax checking. Testing with MacVim (version 7.3) on Snow Leopard, Vimerl works well with GUI and on CLI.

I am going to disable syntax checking when the Vim version is below 7.3, that should hide the errors.
