### ISSUE TITLE
Vim on mac freezes when quitting file

### ISSUE THREAD

**Issue by djnym** [jimenezrick/vimerl#55]
vim 7.3
erlang R16B02

Reproduce with

% vim foo.erl
Then enter ':q'

ps shows

/usr/local/lib/erlang/erts-5.10.1/bin/beam.smp -B -- -root /usr/local/lib/erlang -progname erl -- -home /Users/molinaro -- -boot start_clean -noshell -noshell -noinput -run escript start -extra /Users/molinaro/projects/personal/dotfiles/vim/bundle/vimerl/indent/erlang_indent.erl /Users/molinaro/projects/personal/dotfiles/vim/bundle/vimerl/indent/vimerl_out_fifo.4108 /Users/molinaro/projects/personal/dotfiles/vim/bundle/vimerl/indent/vimerl_in_fifo.4108

and activity monitor shows beam.smp running at 100% CPU.  Eventually the file closes after about 90 seconds.

Commenting out '-mode(compile)' in erlang_indent.erl seems to fix it though.

**Comment by jimenezrick** [comment]
Troubles only on quitting, not in insert mode? Related to issue #44?

**Comment by jimenezrick** [comment]
On Linux using Vim 7.4 and OTP R16B02 works fine. I don't have an Apple computer, thus without additional details I can't see what is happening.

An alternative solution is, try with Vim 7.4 and the latest Vimerl as this Vim runtime ships an official Erlang indentation script (pure Vimscript) which should solve your issues, because my indentation script (which uses beam) it's not used.
